version: '3.9'

services:
  nuxt:
    container_name: rydeen-nuxt
    build:
      context: .
      dockerfile: ./docker/nuxt/Dockerfile
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      # - node_modules_volume:/app/node_modules
    ports:
      - "3001:3001"

# volumes:
#   node_modules_volume:
